Update check-lvm-thinpool

diff --git a/check-lvm-thinpool b/check-lvm-thinpool
--- a/check-lvm-thinpool
+++ b/check-lvm-thinpool
@@ -1,102 +1,320 @@
-#!/usr/bin/perl
-use strict;
-use warnings;
-use Getopt::Long;
+#!/bin/bash
 
-my $warn = 92.0;
-my $crit = 96.0;
+# VERSION 1.2 - 2018-01-25
+# VERSION 1.3 - 2018-05-10 - Add Gui Notify
+#
+# check_lvm_ThinPool - check usage of lvm ThinPool
+#
+# Copyright (C) 2018 Alban Vidal <alban.vidal@zordhak.fr>
+#
+# GNU GENERAL PUBLIC LICENSE Version 3
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-sub get_thinpools {
-  $ENV{'LC_ALL'} = 'C';  # Set locale for lvs call
-  my @lvsoutput = `lvs --noheadings --separator : --select 'lv_attr =~ ^t' -o lv_attr,lv_name,data_percent,metadata_percent`;
-  my @thinpools;
+################################################################################
+##########                       Exit number list:                    ########## 
+################################################################################
+# 0 OK
+# 1 WARNING
+# 2 CRITICAL
+# 3 UNKNOWN         Unknown Invalid command line arguments - see error bellow
 
-  for my $lvsline (@lvsoutput) {
-    if ($lvsline =~ m#^(?:\s+)?(.*):(.*):(.*):(.*)#x) {
-      my $lv = {
-        'lv_attr'          => $1,
-        'lv_name'          => $2,
-        'data_percent'     => $3,
-        'metadata_percent' => $4,
-      };
+################################################################################
+##########                   Exit error number list:                  ########## 
+################################################################################
+# 4 ()              Unknown option $1                                           
+# 5 ()              < 2 opts
+# 6 ()              WARNING $WARNING can t be upper or equal to CRITICAL $CRITICAL 
+# 7 ()              please launch with sudo
+# 8 ()              vg $vg_name does not exist
+# 9 ()              lv $lv_name does not exist or is not in vg $vg_name
+# 10()              is not a thin-pool type, type is: ...
+# 12 (check_int)    $1 opts: option is empty
+# 13 (check_int)    $1 opts: $2 is not a number
+# 14 (check_int)    $1 opts: $2 need interval between 0-100
+# 16                binary not known
+# 17                Performance data is not compatible with GUI notification mode
 
-      push @thinpools, $lv;
-    }
-  }
+################################################################################
+##########                        DEFAULTS OPTIONS                    ##########
+################################################################################
+WARNING=80
+CRITICAL=90
+PERF_DATA=false
+GUI_NOTIFY=false
 
-  return @thinpools;
+################################################################################
+
+_SCRIPT_NAME_=${0##*/}
+
+# Print error messages
+function error()
+{
+    exit_nb=$1
+    shift
+    # NOTE: don't redirect in stderr « >&2 » , else nrpe can't read output
+#    echo "ERROR $exit_nb: $@" >&2
+    echo "ERROR $exit_nb: $@"
+    exit 3
 }
 
-sub check_thinpools {
-  for my $thinpool (get_thinpools()) {
-    # Check metadata usage
-    if ($thinpool->{metadata_percent} > $crit) {
-      add_error(2, "CRITICAL: Meta% of $thinpool->{lv_name} is $thinpool->{metadata_percent}")
-    } elsif ($thinpool->{metadata_percent} > $warn) {
-      add_error(1, "WARNING: Meta% of $thinpool->{lv_name} is $thinpool->{metadata_percent}")
-    }
+# Usage (called by -h or --help)
+function usage()
+{
 
-    # Check data usage
-    if ($thinpool->{data_percent} > $crit) {
-      add_error(2, "CRITICAL: Data% of $thinpool->{lv_name} is $thinpool->{data_percent}")
-    } elsif ($thinpool->{data_percent} > $warn) {
-      add_error(1, "WARNING: Data% of $thinpool->{lv_name} is $thinpool->{data_percent}")
-    }
-  }
-
-  return;
+    echo "Usage: $_SCRIPT_NAME_ [options] vg_name lv_name"
+    echo "Options:"
+    echo "    -w, --warning  <percent>    Define usage warning percent (between 0-100, default: 80)"
+    echo "    -c, --critical <percent>    Define usage critical percent (between 0-100, default: 100)"
+    echo "    -p, --perf-data             Enable performance data output"
+    echo "    -g, --gui-notify <user>     Enable GUI notification mode for Desktop usage"
+    echo "    -e, --examples              Show usage examples"
+    echo "    -h, --help                  Print this help"
+    echo ""
+    echo "------------------------------------------------------------------------------------------"
+    echo "    check_lvm_ThinPool Copyright (C) 2018 Alban Vidal <alban.vidal@zordhak.fr>"
+    echo "    This program comes with ABSOLUTELY NO WARRANTY"
+    echo "    This is free software, and you are welcome to redistribute it under certain conditions"
+    echo "    GNU GENERAL PUBLIC LICENSE Version 3"
+    exit 0
 }
 
-my @errors;
+function examples()
+{
+    yellow="$(tput setaf 3)"
+    green="$(tput setaf 2)"
+    reset="$(tput sgr0)"
+    echo ""
+    echo "${yellow}                          ** Usage examples **${reset}"
+    echo ""
+    echo "${green}Simple check:${reset}"
+    echo "${yellow}check_lvm_ThinPool vg_srv-1 LXDThinpool${reset}"
+    echo "    OK - ThinPool vg_srv-1/LXDThinpool: data=63,40% snap=63,40% meta=32,76%"
+    echo ""
+    echo "${green}Change range Waning and Critical:${reset}"
+    echo "${yellow}check_lvm_ThinPool -w 50 -c 60 vg_srv-1 LXDThinpool${reset}"
+    echo "    CRITICAL - ThinPool vg_srv-1/LXDThinpool: data=63,41% snap=63,41% meta=32,76%"
+    echo ""
+    echo "${green}Desktop usage (GUI notification):${reset}"
+    echo "(change <user> by the graphical user)"
+    echo "${yellow}check_lvm_ThinPool --gui-notify <user> vg_port lv_ThinPool${reset}"
+    echo "    (No CLI output, just in notification area)"
+    echo "    LVM ThinPool Alert"
+    echo "    ThinPool vg_port/lv_ThinPool data=61,03% snap=61,03% meta=20,11%"
+    echo "    "
+    echo ""
 
-sub add_error {
-  my ($exit_code, $message) = @_;
-
-  push @errors, {
-    'exit_code' => $exit_code,
-    'message'   => $message,
-  };
-
-  return;
+    exit 0
 }
 
-sub aggregate_errors {
-  # Sort errors, highest exit code first
-  my @sorted_errors = sort { $b->{exit_code} cmp $a->{exit_code} } @errors;
-  if (scalar @sorted_errors != 0) {
-    for my $error (@sorted_errors) {
-      print $error->{message}, "\n";
-    }
-    exit $sorted_errors[0]->{exit_code};
-  }
-
-  return;
+function check_binary()
+{
+    # $1 => binary to check
+    # $2 => package containing the binary
+    if ! which $1 > /dev/null 2>&1 ;then
+        error 16 $1: binary not known. Please install $2 package or check your '$PATH'
+    fi
 }
 
+# Check number in -w and -c opts
+function check_number()
+{
+    # $1 => arg
+    # $2 => number to check
 
-my $no_thinpools_ok = 0;
-Getopt::Long::Configure('bundling');
-GetOptions
-    ("no-thinpools-ok"  => \$no_thinpools_ok,
-     "w=f" => \$warn, "warning=f" => \$warn,
-     "c=f" => \$crit, "critical=f" => \$crit)
-    or die("Error in command line arguments\n");
+    # Check if not empty
+    if [[ $2 == "" ]]
+    then
+        error 12 $1 opts: option is empty - require a number
+    fi
 
-my @thinpools = get_thinpools();
+    # Check if is number
+    if ! [[ $2 =~ ^[0-9]+$ ]] # OK
+    then
+        error 13 $1 opts: $2 is not a number
+    fi
 
-# No thinpool found?
-if (scalar @thinpools == 0) {
-  if ($no_thinpools_ok == 1) {
-    print "OK: No thinpools found.\n";
-    exit 0;
-  } else {
-    print "UNKNOWN: No thinpools found.\n";
-    exit 3;
-  }
-} else {
-  check_thinpools();
-  aggregate_errors();
+    # Check if > 0 and < 100
+    if ! [ "$2" -ge 0 -a "$2" -le 100 ]
+    then
+        error 14 $1 opts: $2 need interval between 0-100
+    fi
 }
 
-print "OK - All thinpools OK\n";
-exit 0;
+# Check args
+opt="$1"
+while test ! -z "$opt" -a -z "${opt##-*}"
+do
+
+    case "$opt" in
+        "-h"|"--help")
+            usage
+            ;;
+        "-e"|"--examples")
+            examples
+            ;;
+        "-w"|"--warning")
+            check_number warning $2 
+            WARNING=$2
+            shift
+            ;;
+        "-c"|"--critical")
+            check_number critical $2
+            CRITICAL=$2
+            shift
+            ;;
+        "-p"|"--perf-data")
+            PERF_DATA=true # Enable performance data output
+            ;;
+        "-g"|"--gui-notify")
+            # Check if notify-send binary is available
+            check_binary notify-send libnotify-bin
+            GUI_USER=$2
+            GUI_NOTIFY=true
+            shift
+            ;;
+        *)
+            error 4 Unknown option: $1
+            ;;
+    esac
+
+    shift
+    opt="$1"
+done
+
+# TEST if PERF_DATA=true AND GUI_NOTIFY=true
+if $PERF_DATA && $GUI_NOTIFY ; then
+    error 17 "Performance data is not compatible with GUI notification mode"
+fi
+
+# TEST if WARN > to CRIT => ERR
+if [ $WARNING -ge $CRITICAL ] ;then
+    error 6 WARNING \($WARNING\) can\'t be upper or equal to CRITICAL \($CRITICAL\)
+fi
+
+# Check binary
+check_binary lvs lvm2
+check_binary awk gawk
+
+# Test if remaining arg is two: <vg> and <lv>
+if [ ! $# -eq 2 ]
+then
+    error 5 vg_name and lv_name is required, to usage see: $_SCRIPT_NAME_ --help
+fi
+
+# Check if we are root right
+if [ $(id -u) -ne 0 ];then
+    error 7 please launch with sudo
+fi
+
+vg_name="$1"
+lv_name="$2"
+
+# Check if <vg> exist
+if ! vgs $vg_name > /dev/null 2>&1 ; then
+    error 8 vg $vg_name does not exist
+fi
+
+# Check if <lv> exist ans if is an thin lv pool
+#if ! lv_result=$(lvs ${vg_name}/${lv_name}) 2>/dev/null ; then
+if ! lv_result=$(lvs --noheading --separator "__" --options vg_name,lv_name,attr,segtype,data_percent,snap_percent,metadata_percent ${vg_name}/${lv_name} 2>/dev/null ) ; then
+    error 9 lv $lv_name does not exist or is not in vg $vg_name
+fi
+
+# end of tests
+################################################################################
+# NOTE:
+# 1 = vg_name               vg_foo
+# 2 = lv_name               lv_bar
+# 3 = attr                  -wi-a-----
+# 4 = segtype               linear=error / thin-pool=OK
+# 5 = data_percent          xx,xx
+# 6 = snap_percent          yy,yy
+# 7 = metadata_percent      zz,zz
+
+# Test if is thinpool
+# if is not thinPool type, we return current type
+test_thinpool=$(echo $lv_result| \
+awk -F __ \
+    '{ if ($4 == "thin-pool")  print "OK"; else print $1 "/" $2 "is not a thin-pool type, type is: " $4 }')
+if ! echo $test_thinpool|grep -q ^OK$ ; then
+    error 10 $test_thinpool
+fi
+
+# number of warning and critical error
+number_WARN=0
+number_CRIT=0
+
+function check_percent()
+{
+    # $1 = percent
+    local percent=$1
+    # remove , or .
+    percent=${percent%%,*}
+    percent=${percent%%.*}
+    if [ $percent -gt $CRITICAL ] ; then
+        (( number_CRIT ++ ))
+    elif [ $percent -gt $WARNING ] ; then
+        (( number_WARN ++ ))
+    fi
+}
+
+# data_percent
+data_percent=$(echo $lv_result| awk -F __ '{print $5}')
+check_percent $data_percent
+
+# snap_percent
+snap_percent=$(echo $lv_result| awk -F __ '{print $6}')
+check_percent $snap_percent
+
+# metadata_percent
+metadata_percent=$(echo $lv_result| awk -F __ '{print $7}')
+check_percent $metadata_percent
+
+output="- ThinPool ${vg_name}/${lv_name} data=${data_percent}% snap=${snap_percent}% meta=${metadata_percent}%"
+
+if [ $number_CRIT -gt 0 ] ; then   # CRITICAL
+    output_prefix="CRITICAL"
+    exit_code=2
+elif [ $number_WARN -gt 0 ] ; then # WARNING
+    output_prefix="WARNING"
+    exit_code=1
+else                               # OK
+    output_prefix="OK"
+    exit_code=0
+fi
+
+if ! $GUI_NOTIFY ; then
+    # CLI mode (nagios, icinga....)
+    # Print output :
+    echo "$output_prefix $output"
+    if $PERF_DATA ; then
+        echo " | ${vg_name}/${lv_name}_data=${data_percent}% ${vg_name}/${lv_name}_snap=${snap_percent}% ${vg_name}/${lv_name}_meta=${metadata_percent}%"
+    fi
+else
+    # GUI mode
+    # Notify only if return code is not 0
+    if [ $exit_code -ne 0 ] ; then
+        export HOME="/home/$GUI_USER"
+        export DISPLAY=:0.0
+        EXPIRE_TIME=60000 # 60 seconds
+        notify-send --icon=drive-multidisk --urgency=critical --expire-time=$EXPIRE_TIME "LVM ThinPool Alert" "$output_prefix $output"
+    fi
+    # In GUI mode, wee need to exit code is equal to 0 if systemd is used
+    exit 0
+fi
+
+exit $exit_code
+
+################################################################################
